Us04 sprint01 photo before after
WildCodeSchool/orleans-0219-php-renoving-habitat pull request #10
Opened 2019-06-06 11:54 UTC by AngelRionCervi

2019-06-06 13:49 UTC, jaffar45 approved these changes

2019-06-06 13:51 UTC, ManuWiizzle approved these changes

2019-06-07 07:45 UTC, BertrandGouny commented on webpack.config.js
> +    .addEntry('juxtapose', './assets/js/juxtapose.js')
Utiliser yarn et webpack-encore pour les librairies JS

2019-06-11 09:42 UTC, TortueNina approved these changes

2019-06-11 10:21 UTC, BertrandGouny commented on assets/js/juxtapose.js
> +/* juxtapose - v1.2.1 - 2019-04-18
utiliser yarn pour les librairies externes

2019-06-11 10:21 UTC, BertrandGouny commented on assets/scss/juxtapose.scss
> +/* juxtapose - v1.2.1 - 2019-04-18
importer depuis node_modules après avoir utilisé yarn pour gérer les librairies externes

2019-06-11 13:43 UTC, jaffar45 approved these changes

2019-06-12 12:20 UTC, BertrandGouny commented
Supprimer les fichiers des librairies externes dans assets

2019-06-12 13:53 UTC, BertrandGouny requested changes

2019-06-12 13:53 UTC, BertrandGouny commented on templates/home/index.html.twig
> +    {{ encore_entry_script_tags('juxtapose') }}
plus nécessaire

2019-06-12 13:53 UTC, BertrandGouny commented on webpack.config.js
> +;erge
;erge ?

2019-06-12 14:11 UTC, merged