Style home
WildCodeSchool/orleans-0219-php-renoving-habitat pull request #22
Opened 2019-06-19 15:45 UTC by TortueNina

2019-06-20 12:13 UTC, AngelRionCervi approved these changes

2019-06-20 13:12 UTC, BertrandGouny requested changes

2019-06-20 13:12 UTC, BertrandGouny commented on assets/scss/footer.scss
> +  box-shadow: -2px -7px 29px -5px rgba(199,197,199,1);
couleur dans une variable

2019-06-20 13:12 UTC, BertrandGouny commented on assets/scss/footer.scss
> +    background: transparent;
couleur dans une variable

2019-06-20 13:12 UTC, BertrandGouny commented on assets/scss/footer.scss
> +    border-top: 2.5em solid transparent;
pourquoi rajouter une border transparente ?

2019-06-20 13:12 UTC, BertrandGouny commented on assets/scss/homepage.scss
> +    box-shadow: inset -5px -4px 13px -8px rgba(133,130,133,1);
couleur dans une variable

2019-06-20 13:12 UTC, BertrandGouny commented on assets/scss/homepage.scss
> +.bonPlans {
nom des classes en kebab-case

2019-06-20 13:12 UTC, BertrandGouny commented on assets/scss/homepage.scss
> +  .logoPartenaires {
nom des classes en kebab-case

2019-06-20 13:12 UTC, BertrandGouny commented on assets/scss/homepage.scss
> +    font-family: 'Patrick Hand', cursive;
font dans une variable

2019-06-20 13:12 UTC, BertrandGouny commented on templates/base.html.twig
> +            <script src="https://kit.fontawesome.com/6247ba9520.js"></script>
utiliser yarn pour fontawesome

2019-06-20 13:12 UTC, BertrandGouny commented on templates/footer/index.html.twig
> +                                <a href="#" class="footer_links stretched-link">NOUS RECRUTONS</a>
écrire en minuscule "Nous recrutons" et passer en majuscule avec le css

2019-06-20 13:12 UTC, BertrandGouny commented on templates/footer/index.html.twig
> +                    <a class="logo" href="/"><img src="/assets/images/logo_no_back.png" alt="RenovingHabitat"></a>
Utiliser la methode {{ asset('build/logo.png') }} 
https://symfony.com/doc/current/frontend/encore/copy-files.html

2019-06-20 13:31 UTC, TortueNina commented on assets/scss/footer.scss
> +    border-top: 2.5em solid transparent;
Pour l'épaisseur. En hover, il ne l'est pas...

2019-06-20 13:38 UTC, BertrandGouny requested changes

2019-06-20 13:38 UTC, BertrandGouny commented on templates/home/index.html.twig
> +                        <a href="" class="stretched-link"><img src="/assets/partenaires/rockwool.gif" width="99%" alt="rockwool-logo"></a>
utiliser la méthode webpack pour faire appel a tous les assets 
https://symfony.com/doc/current/frontend/encore/copy-files.html

2019-06-21 08:36 UTC, BertrandGouny commented
Le nom de la branche doit correspondre à une US ou à un fix

2019-06-25 09:09 UTC, closed without merging