Sprint03 us18 formulaire recrutment file upload
WildCodeSchool/orleans-0219-php-renoving-habitat pull request #23
Opened 2019-06-20 07:45 UTC by jaffar45

2019-06-20 09:29 UTC, ManuWiizzle approved these changes

2019-06-20 13:46 UTC, TortueNina approved these changes

2019-06-21 08:30 UTC, BertrandGouny commented on assets/js/fixUpload.js
> +$('#cv_upload_cv').on('change', function () {
nom fichier en _

2019-06-21 08:30 UTC, BertrandGouny commented on config/packages/vich_uploader.yaml
> +vich_uploader:
vich est plus utilisé ?

2019-06-21 08:30 UTC, BertrandGouny commented on src/Controller/RecruitmentController.php
> +                ->attach(Swift_Attachment::fromPath($cv->getPathname()))
modifier le nom du fichier en piece jointe

2019-06-21 08:30 UTC, BertrandGouny commented on src/Entity/CvUpload.php
> +     * @Assert\Length(min=1, max=100)
supprimer le min=1, unutile avec NotBlank

2019-06-21 08:30 UTC, BertrandGouny commented on src/Entity/CvUpload.php
> +    private $occupation;
ajouter commentaire

2019-06-21 08:30 UTC, BertrandGouny commented on src/Entity/CvUpload.php
> +    private $area;
+1

2019-06-21 08:30 UTC, BertrandGouny commented on src/Form/RecruitmentType.php
> +<?php
plus utilisé ?

2019-06-21 08:30 UTC, BertrandGouny commented on src/Repository/CvUploadRepository.php
> +    // /**
supprimer le code commenté

2019-06-24 07:53 UTC, AngelRionCervi approved these changes

2019-06-24 08:07 UTC, TortueNina approved these changes

2019-06-25 07:39 UTC, BertrandGouny requested changes

2019-06-25 07:39 UTC, BertrandGouny commented on webpack.config.js
> +    .addEntry('fixUpload', './assets/js/fixUpload.js')
fix_upload.js

2019-06-25 08:22 UTC, merged