Mon projet
WildCodeSchool/orleans-0219-php-renoving-habitat pull request #24
Opened 2019-06-20 13:58 UTC by AngelRionCervi

2019-06-20 14:05 UTC, jaffar45 approved these changes

2019-06-20 14:12 UTC, jaffar45 approved these changes

2019-06-21 08:36 UTC, BertrandGouny commented
Le nom de la branche doit correspondre à une US ou à un fix

2019-06-21 08:56 UTC, BertrandGouny commented on assets/js/monProjet.js
> +const Swal = require('sweetalert2')
nom du fichier avec _

2019-06-21 08:56 UTC, BertrandGouny commented on assets/scss/icons.scss
> +/*!
inclure fontawesome avec yarn

2019-06-21 08:56 UTC, BertrandGouny commented on assets/scss/app.scss
> +    color: blue;
couleur dans une variable

2019-06-21 08:56 UTC, BertrandGouny commented on assets/scss/mon_projet.scss
> +   background-color: #ccc;
couleur dans une variable

2019-06-21 08:56 UTC, BertrandGouny commented on assets/scss/mon_projet.scss
> +   background-color: white;
couleur dans une variable

2019-06-21 08:56 UTC, BertrandGouny commented on assets/scss/mon_projet.scss
> +   font-family: "FontAwesome";
font dans une variable

2019-06-21 08:56 UTC, BertrandGouny commented on public/php/sendEmailMonProjet.php
> +<?php
FIchier de dev ?

2019-06-21 08:56 UTC, BertrandGouny commented on src/Controller/MonProjetController.php
> +     * @Route("/projet/sendEmail", name="emailSend")
nom des routes en snake case par convention

2019-06-21 08:56 UTC, BertrandGouny commented on src/Entity/FormCouverture.php
> +    private $DernierTraitement;
nom des attributs en camelCase + ajouter des asserts

2019-06-21 08:56 UTC, BertrandGouny commented on src/Repository/MainWorkCategoriesRepository.php
> +    // /**
supprimer le code commenté

2019-06-21 08:56 UTC, BertrandGouny commented on src/Controller/MonProjetController.php
> +/**
supprimer

2019-06-21 08:56 UTC, BertrandGouny commented on src/Service/MyProjectEmailSender.php
> +/**
supprimer

2019-06-21 08:56 UTC, BertrandGouny commented on templates/monProjet/forms/formChauffage.html.twig
> +<div class="col-md-6 form_projet" id="formChauffage">
creer des formtype pour tous les formulaires

2019-06-21 08:56 UTC, BertrandGouny commented on assets/js/monProjet.js
> +        document.querySelector('#formCouverture'),
utiliser des classes

2019-06-24 07:59 UTC, jaffar45 approved these changes

2019-06-24 08:03 UTC, TortueNina approved these changes

2019-07-01 11:44 UTC, jaffar45 approved these changes

2019-07-01 12:25 UTC, BertrandGouny requested changes

2019-07-01 12:25 UTC, BertrandGouny commented on assets/js/mon_projet.js
> +    /*document.getElementById('sendAllForms').addEventListener('click', () => {
supprimer code commenté

2019-07-01 12:25 UTC, BertrandGouny commented on public/php/sendEmailMonProjet.php
> +<?php
Fichier à supprimer

2019-07-01 12:25 UTC, BertrandGouny commented on src/Entity/Bathroom.php
> +/**
supprimer toutes les annotation @orm sur les entités qui sont pas persistées en bdd

2019-07-01 12:25 UTC, BertrandGouny commented on src/Repository/BathroomRepository.php
> +<?php
supprimer les repository non utilisés

2019-07-01 12:25 UTC, BertrandGouny commented on templates/monProjet/forms/formChauffage.html.twig
> +<div class="col-md-6 form_projet" id="formChauffage">
fichier plus utilisé ?

2019-07-01 12:25 UTC, BertrandGouny commented on templates/monProjet/forms/formCouverture.html.twig
> +<div class="col-md-6 form_projet" id="formCouverture">
fichier plus utilisé ?

2019-07-01 12:25 UTC, BertrandGouny commented on templates/monProjet/forms/formRavalement.html.twig
> +<div class="col-md-6 form_projet" id="formRavalement">
fichier plus utilisé ?

2019-07-01 12:25 UTC, BertrandGouny commented on templates/monProjet/forms/formSalleDeBain.html.twig
> +<div class="col-md-6 form_projet" id="formSalleDeBain">
fichier plus utilisé ?

2019-07-01 12:25 UTC, BertrandGouny commented on templates/monProjet/forms/formTerrassement.html.twig
> +<div class="col-md-6 form_projet" id="formTerrassement">
fichier plus utilisé ?

2019-07-01 12:25 UTC, BertrandGouny commented on templates/monProjet/forms/formTravauxInterieur.html.twig
> +<div class="col-md-6 form_projet" id="formTravauxInterieur">
fichier plus utilisé ?

2019-07-01 14:10 UTC, BertrandGouny requested changes

2019-07-01 14:10 UTC, BertrandGouny commented on src/Controller/MyProjectController.php
> +                'Votre demande de devis a été envoyé, nous vous recontacterons bientôt!'
envoyée

2019-07-01 14:10 UTC, BertrandGouny commented on src/Entity/Bathroom.php
> +    private $id;
supprimer l'id

2019-07-01 14:10 UTC, BertrandGouny commented on src/Entity/Bathroom.php
> +    public function getId(): ?int
et son getter

2019-07-01 14:10 UTC, BertrandGouny commented on src/Entity/Roofing.php
> +/**
A gardé ses annotation ORM?

2019-07-01 15:01 UTC, BertrandGouny requested changes

2019-07-01 15:01 UTC, BertrandGouny commented on src/Entity/MainWorkCategories.php
> +    private $id;
reste un id ici :)

2019-07-01 15:01 UTC, BertrandGouny commented on src/Entity/MyProjectPersonal.php
> +    private $id;
reste un id

2019-07-01 15:01 UTC, BertrandGouny commented on src/Entity/MyProjectPersonal.php
> +    public function getId(): ?int
retirer le getter aussi

2019-07-01 15:01 UTC, BertrandGouny commented on src/Entity/MainWorkCategories.php
> +    public function getId(): ?int
retirer le getter aussi

2019-07-01 15:47 UTC, BertrandGouny commented on src/Entity/MainWorkCategories.php
> +    private $Couverture;
enlever les majuscules des propriétés

2019-07-01 15:47 UTC, BertrandGouny commented on src/Entity/MainWorkCategories.php
> +    private $Couverture;
+ en anglais

2019-07-01 15:47 UTC, BertrandGouny commented on templates/monProjet/index.html.twig
> +                                 src="assets/mon_projet_image/travaux_interieur.jpg" alt="Travaux intérieur">
pas d'assets en dur (voir avec Vanina)

2019-07-01 20:07 UTC, merged