added readme
WildCodeSchool/orleans-0219-php-renoving-habitat pull request #61
Opened 2019-07-09 12:21 UTC by AngelRionCervi

2019-07-09 12:50 UTC, BertrandGouny commented on readme.MD
> +Modify these 2 lines in the .env file
.env.local

2019-07-09 12:50 UTC, BertrandGouny commented on readme.MD
> +following the exemples in the file.
example

2019-07-09 12:50 UTC, BertrandGouny commented on readme.MD
> +then : "php bin/console doctrine:migration:migrate" to update the database.
création du schéma avant

2019-07-09 12:50 UTC, BertrandGouny commented on readme.MD
> +"npm run dev" to build the website, "php bin/console server:run" to serve it.
run dev ? non

2019-07-09 13:24 UTC, jaffar45 approved these changes

2019-07-10 07:55 UTC, BertrandGouny requested changes

2019-07-10 07:55 UTC, BertrandGouny commented on readme.MD
> +"npm install"
yarn :)

2019-07-10 07:55 UTC, BertrandGouny commented on readme.MD
> +clone the repo then :
Développer plus et faire soigner un peu plus la mise en forme,
tu peux prendre exemple sur : https://github.com/WildCodeSchool/orleans-0219-php-lavoliere

2019-07-22 09:55 UTC, closed without merging