Us03 sprint01 home picture
WildCodeSchool/orleans-0219-php-renoving-habitat pull request #9
Opened 2019-06-06 07:34 UTC by AngelRionCervi

2019-06-06 07:37 UTC, jaffar45 approved these changes

2019-06-06 13:50 UTC, jaffar45 approved these changes

2019-06-06 14:33 UTC, ManuWiizzle approved these changes

2019-06-07 07:41 UTC, BertrandGouny commented on templates/home/index.html.twig
> +    <script
Utiliser yarn et webpack-encore pour les librairies JS

2019-06-11 10:34 UTC, BertrandGouny requested changes

2019-06-11 10:34 UTC, BertrandGouny commented on assets/js/mapResizer2.js
> +/*
utiliser yarn pour les librairies externes

2019-06-11 10:34 UTC, BertrandGouny commented on assets/js/maph.js
> +(function(root, factory) {
utiliser yarn pour les librairies externes

2019-06-11 10:34 UTC, BertrandGouny commented on assets/js/tooltipster.bundle.js
> +/**
utiliser yarn pour les librairies externes

2019-06-11 10:34 UTC, BertrandGouny commented on webpack.config.js
> +    .addEntry('tooltipster', './assets/js/tooltipster.bundle.js')
utiliser yarn pour les librairies externes

2019-06-12 12:28 UTC, BertrandGouny commented on public/assets/js/mapster.js
> +/* ImageMapster
utiliser https://www.npmjs.com/package/jquery-imagemapster

2019-06-12 12:28 UTC, BertrandGouny commented on public/assets/js/mapper.js
> +/* mapper.js 2.4 (10-Aug-2010) (c) by Christian Effenberger. All Rights Reserved. Source: mapper.netzgesta.de. Distributed under Netzgestade Software License Agreement. Read more at... http://www.net
Utiliser https://www.npmjs.com/package/mapperjs si c'est la même librairie

2019-06-12 12:28 UTC, BertrandGouny commented on public/assets/js/tooltipster.bundle.js
> +/**
Inclure la librarie avec yarn et supprimer le fichier

2019-06-12 15:46 UTC, merged